### ISSUE TITLE
0103 星期日課程的例子:各鄉鎮市區人口密度

### ISSUE THREAD

**Issue by microfate** [roberthsu2003/python#9]
![例子](https://user-images.githubusercontent.com/76903439/103477760-b349fd00-4dfc-11eb-9f2d-2394313f5fbd.png)
老師:
我想把 if '竹南' in newone[1]: 改成input的方式.
但我寫成input後無法讓 input被判斷並落入 print(newone)

import csv
with open('各鄉鎮市區人口密度.csv', 'r', encoding='utf8') as file:
    csvReader = csv.reader(file)
    poplist = []
    for one in csvReader:
        if one[0] == '106':
            poplist.append(one)
    
    for newone in poplist:
        name = (input("請輸入查詢縣市名:"))
        if name in newone[1]:
            print(newone)

**Comment by DerrickHsiao** [comment]
把input放在for in 上面
記得區塊要跟for in並齊～

name = (input("請輸入查詢縣市名:"))
for newone in poplist:
    if name in newone[1]:
        print(newone)

**Comment by microfate** [comment]
> 把input放在for in 上面
> 記得區塊要跟for in並齊～
> 
> name = (input("請輸入查詢縣市名:"))
> for newone in poplist:
> if name in newone[1]:
> print(newone)

Hi  感 謝 回應 ~ 但仍有問題.如果完 全並排會有error,若有分開就只能輸入一次名字且也無法落 入 if name in newone[1] and print
![Screen Shot 2021-01-04 at 20 02 34](https://user-images.githubusercontent.com/76903439/103533411-05a42000-4ec8-11eb-8a76-234a5786c194.png)
![Screen Shot 2021-01-04 at 20 02 02](https://user-images.githubusercontent.com/76903439/103533420-0a68d400-4ec8-11eb-9351-8c0b30fd667a.png)

**Comment by DerrickHsiao** [comment]
沒有啦！只有input那行要跟下面的for in並排啦😅
抱歉表達不清楚

**Comment by microfate** [comment]
Hi 
成功了~謝謝 
![Screen Shot 2021-01-04 at 21 44 44](https://user-images.githubusercontent.com/76903439/103541312-39864200-4ed6-11eb-8eed-a942aa799e31.png)



> 把input放在for in 上面
> 記得區塊要跟for in並齊～
> 
> name = (input("請輸入查詢縣市名:"))
> for newone in poplist:
> if name in newone[1]:
> print(newone)
